name: 'ZIP TO ARTIFACT'
description: 'Zip a NODE/NEXT project and publish a zip file to Artifact'
inputs:
  production:
    description: 'Is this a production build?'
    required: true
    default: 'true'
  retention_days:
    description: 'Retention Days'
    required: true
    default: 1
runs:
  using: 'composite'
  steps:
  - name: GET VERSION
    id: package-version
    uses: martinbeentjes/npm-get-version-action@master
  - name: 'Set Production:'
    run: echo "PROD=$(${{ inputs.production == 'true' }} && echo '' || echo '-s')" >> $GITHUB_ENV
    shell: bash
  - name: ZIP
    uses: vimtor/action-zip@master
    with:
      files: ".next/ next/ dist/ public/ node_modules/ package.json"
      dest: zip/${{ steps.package-version.outputs.current-version }}${{ env.PROD }}.zip
      recursive: false
  - name: 'Upload Artifact to Production:${{ inputs.production }}'
    uses: actions/upload-artifact@v2
    with:
      name: ${{ steps.package-version.outputs.current-version }}${{ env.PROD }}.zip
      path: zip/${{ steps.package-version.outputs.current-version }}${{ env.PROD }}.zip
      retention-days: ${{inputs.retention_days}}
